// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjSala.Models;

namespace ProjSala.Migrations
{
    [DbContext(typeof(MvcSalaContext))]
    partial class MvcSalaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ProjSala.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cidade");

                    b.Property<string>("nome");

                    b.Property<int>("qtdeAlunos");

                    b.Property<int>("qtdeProdessores");

                    b.Property<string>("telefone");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });
#pragma warning restore 612, 618
        }
    }
}
